# Disabled dev_profiler routing to avoid errors due to missing WebProfilerBundle
# web_profiler_wdt:
#     resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
#     prefix: /_wdt
#
# web_profiler_profiler:
#     resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
#     prefix: /_profiler
