about:
    path: /about
    controller: App\Controller\HomeController::about

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

conditions:
    path: /conditions
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: conditions.html.twig

confidentialite:
    path: /confidentialite
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: confidentialite.html.twig

cookies:
    path: /cookies
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: cookies.html.twig

parametres:
    path: /parametres
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: parametres.html.twig

conditions:
    path: /conditions.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: conditions.html

confidentialite:
    path: /confidentialite.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: confidentialite.html

cookies:
    path: /cookies.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: cookies.html

parametres:
    path: /parametres.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: parametres.html
