when@dev:
# Disabled web_profiler configuration to avoid errors due to missing WebProfilerBundle
# web_profiler:
#     toolbar: true
#     intercept_redirects: false

    framework:
        profiler: { only_exceptions: false }

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
